import{S,a as v,i as m}from"./assets/vendor-951421c8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const w="https://pixabay.com/api/",k="41985459-07284690ed1bbc3dd300f203e",q=document.querySelector(".form"),g=document.querySelector(".gallery"),f=document.querySelector(".loader"),l=document.querySelector(".load-button"),a="is-hidden";let d="",u=1,h=0;const C=new S(".gallery-item a",{captionsData:"alt",captionDelay:250});q.addEventListener("submit",$);async function $(o){o.preventDefault(),g.innerHTML="",u=1,f.classList.remove(a);const s=o.currentTarget;if(d=s.elements.query.value,!d){l.classList.add(a),c();return}try{const t=await y(d);h=Math.ceil(t.totalHits/40),L(t),t.hits.length>0&&t.hits.length!==t.totalHits?(l.classList.remove(a),l.addEventListener("click",p)):t.hits.length?l.classList.add(a):(l.classList.add(a),c())}catch{c()}finally{f.classList.add(a),s.reset()}}async function y(o,s=1){try{return(await v.get(`${w}`,{params:{key:k,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:40}})).data}catch{c()}}async function p(){u+=1,x(),l.disabled=!0,f.classList.remove(a);try{const o=await y(d,u);L(o)}catch{c()}finally{l.disabled=!1,f.classList.add(a),u===h&&(l.classList.add(a),l.removeEventListener("click",p),m.show({title:"Error",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}}function L(o){const s=o.hits.map(({webformatURL:t,largeImageURL:i,tags:e,likes:r,views:n,comments:E,downloads:b})=>`
      <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${t}"
      data-source="${i}"
      alt="${e}"
    />
    <p class= "gallery-text">• Likes: ${r} • Views: ${n} • Comments: ${E} •</span> Downloads:${b}</p>
  </a>
</li>`).join("");g.insertAdjacentHTML("beforeend",s),C.refresh()}function x(){const s=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:s,behavior:"smooth"})}function c(o){m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,progressBarEasing:"linear"})}
//# sourceMappingURL=commonHelpers.js.map
