import{S,a as v,i as m}from"./assets/vendor-951421c8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/",k="41985459-07284690ed1bbc3dd300f203e",q=document.querySelector(".form"),g=document.querySelector(".gallery"),f=document.querySelector(".loader"),n=document.querySelector(".load-button"),C=document.querySelector(".gallery-item"),a="is-hidden";let d="",u=1,h=0;const $=new S(".gallery-item a",{captionsData:"alt",captionDelay:250});q.addEventListener("submit",x);async function x(t){t.preventDefault(),g.innerHTML="",u=1,f.classList.remove(a);const s=t.currentTarget;if(d=s.elements.query.value,!d){n.classList.add(a),c();return}try{const r=await y(d);h=Math.ceil(r.totalHits/40),L(r),r.hits.length>0&&r.hits.length!==r.totalHits?(n.classList.remove(a),n.addEventListener("click",p)):r.hits.length?n.classList.add(a):(n.classList.add(a),c())}catch{c()}finally{f.classList.add(a),s.reset()}}async function y(t,s=1){try{return(await v.get(`${w}`,{params:{key:k,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:40}})).data}catch{c()}}async function p(){u+=1,M(),n.disabled=!0,f.classList.remove(a);try{const t=await y(d,u);L(t)}catch{c()}finally{n.disabled=!1,f.classList.add(a),u===h&&(n.classList.add(a),n.removeEventListener("click",p),m.show({title:"Error",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}}function L(t){const s=t.hits.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:l,comments:b,downloads:E})=>`
      <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${r}"
      data-source="${i}"
      alt="${e}"
    />
    <p class= "gallery-text">• Likes: ${o} • Views: ${l} • Comments: ${b} •</span> Downloads:${E}</p>
  </a>
</li>`).join("");g.insertAdjacentHTML("beforeend",s),$.refresh()}function M(){const t=C.getBoundingClientRect().height*2;window.scrollBy({top:t,behavior:"smooth"})}function c(t){m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,progressBarEasing:"linear"})}
//# sourceMappingURL=commonHelpers.js.map
